#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define ID_SETTINGS_WINDOW                      2
#define ID_ADVANCED_SETTINGS_WINDOW             3
#define ID_BUTTON_SETTINGS                      4
#define ID_CORRELATION_SETTINGS_WINDOW          4
#define ID_PID_SETTINGS_WINDOW                  5
#define ID_SUCCESS_WINDOW                       7
#define ID_ANALYSIS_WINDOW                      9
#define ID_EDITCONTROL_D_8                      9
#define ID_EDITCONTROL_TTL                      9
#define ID_EDITCONTROL_D_7                      10
#define ID_ICON                                 10
#define ID_BUTTON_ADVANCED_SETTINGS             11
#define ID_BUTTON_CONTINUE                      12
#define ID_BUTTON_EXIT                          13
#define ID_EDITCONTROL_D_4                      13
#define ID_EDITCONTROL_D_3                      14
#define ID_EDITCONTROL_LAKESHORE                14
#define ID_STR_BOXCAR_WIDTH                     16
#define ID_STR_WEIGHT_FUNCTION_NAME             17
#define ID_BUTTON_APPLY                         18
#define ID_BUTTON_CANCEL                        19
#define ID_BUTTON_START                         20
#define ID_EDITCONTROL_C                        21
#define ID_EDITCONTROL_GENERATOR                22
#define ID_EDITCONTROL_P_10                     23
#define ID_EDITCONTROL_AI_PULSE                 25
#define ID_EDITCONTROL_DISPERSION               26
#define ID_EDITCONTROL_TIME_CORRELATION         28
#define ID_RADIO_APPEND                         30
#define ID_STR_BEGIN                            31
#define ID_BUTTON_CORRELATION_SETTINGS          32
#define ID_BUTTON_PREVIOUS_WEIGHT_FUNC          33
#define ID_EDITCONTROL_BEGIN                    35
#define ID_EDITCONTROL_DAQ                      36
#define ID_EDITCONTROL_SAVE_FILE_NAME           37
#define ID_EDITCONTROL_END                      39
#define ID_EDITCONTROL_MEASURE_TIME             41
#define ID_EDITCONTROL_OUT_CHANNEL              42
#define ID_RADIO_NEW                            44
#define ID_STR_BOXCAR_ADD_CORRELATION           45
#define ID_BUTTON_CLOSE                         46
#define ID_EDITCONTROL_G                        47
#define ID_EDITCONTROL_WIDTH                    48
#define ID_STR_CHANNEL_A                        50
#define ID_BUTTON_CLOSE_SETTINGS                51
#define ID_BUTTON_PUSH_CORRELATION              54
#define ID_STR_POWER                            56
#define ID_BUTTON_SET                           57
#define ID_EDITCONTROL_BIAS                     58
#define ID_STR_BOXCAR_C                         59
#define ID_LIST_CORRELATION                     61
#define ID_STR_DISPERSION                       62
#define ID_BUTTON_PULL_CORRELATION              63
#define ID_EDITCONTROL_UBOUNDARY_9              66
#define ID_BUTTON_NEXT_RELAXATION               67
#define ID_BUTTON_PID_SETTINGS                  68
#define ID_BUTTON_PREVIOUS_RELAXATION           69
#define ID_EDITCONTROL_UBOUNDARY_8              71
#define ID_STATIC1                              72
#define ID_EDITCONTROL_RATE                     73
#define ID_STR_SETPOINT                         74
#define ID_BUTTON_NEXT_WEIGHT_FUNC              75
#define ID_EDITCONTROL_AVERAGING                76
#define ID_EDITCONTROL_UBOUNDARY_7              77
#define ID_CHECKBOX_FIX_TEMPERATURE             78
#define ID_EDITCONTROL_AI                       79
#define ID_EDITCONTROL_UBOUNDARY_6              80
#define ID_STATIC2                              81
#define ID_EDITCONTROL_PERIOD                   83
#define ID_EDITCONTROL_UBOUNDARY_5              84
#define ID_EDITCONTROL_UBOUNDARY_4              87
#define ID_EDITCONTROL_UBOUNDARY_3              89
#define ID_EDITCONTROL_UBOUNDARY_2              91
#define ID_EDITCONTROL_WIDTHPULSE               92
#define ID_EDITCONTROL_UBOUNDARY_1              93
#define ID_EDITCONTROL_UBOUNDARY_10             94
#define ID_EDITCONTROL_GATE                     95
#define ID_EDITCONTROL_FILE_SAVE_NAME           96
#define ID_EDITCONTROL_I_10                     97
#define ID_EDITCONTROL_I_9                      98
#define ID_EDITCONTROL_I_8                      99
#define ID_EDITCONTROL_I_7                      100
#define ID_EDITCONTROL_I_6                      101
#define ID_EDITCONTROL_I_5                      102
#define ID_EDITCONTROL_I_4                      103
#define ID_EDITCONTROL_I_3                      104
#define ID_EDITCONTROL_I_2                      105
#define ID_EDITCONTROL_I_1                      106
#define ID_EDITCONTROL_D_10                     107
#define ID_EDITCONTROL_D_9                      108
#define ID_EDITCONTROL_D_6                      111
#define ID_EDITCONTROL_D_5                      112
#define ID_BITMAP_OPEN                          114
#define ID_EDITCONTROL_D_2                      115
#define ID_EDITCONTROL_D_1                      116
#define ID_EDITCONTROL_P_9                      117
#define ID_EDITCONTROL_P_8                      118
#define ID_EDITCONTROL_P_7                      119
#define ID_EDITCONTROL_P_6                      120
#define ID_EDITCONTROL_P_5                      121
#define ID_EDITCONTROL_P_4                      122
#define ID_EDITCONTROL_P_3                      123
#define ID_EDITCONTROL_P_2                      124
#define ID_EDITCONTROL_P_1                      125
#define ID_STR_END                              126
#define ID_BUTTON_APPLY_SETTINGS                127
#define ID_EDITCONTROL_STEP                     128
#define ID_EDITCONTROL_EFFECTIVE_MASS           129
#define ID_EDITCONTROL_AMPLITUDE                130
#define ID_BITMAP_SAVE                          132
#define ID_BITMAP_EXIT                          141
#define ID_BITMAP_REPLY                         142
#define ID_BITMAP_NEXT                          143
#define ID_BITMAP_PLOT                          154
#define ID_BITMAP_PLOT_LINEAR                   160
#define ID_BITMAP_PLOT_DLTS_PEAK                162
#define ID_BITMAP_PLOT_EXP                      164
#define ID_BITMAP_PLOT_DLTS                     167
#define ID_IMG_ROSE                             169
#define ID_START_WINDOW_DLTS                    178
#define ID_START_WINDOW_AITS                    181
#define ID_START_WINDOW_BITS                    185
#define ID_CHECKBOX_USE_GENERATOR               555
#define ID_BUTTON_PREVIOUS_W2                   40000
#define ID_CHECKBOX_USE_BSPLINE_DLTS            40000
#define ID_EDITCONTROL_AI_CAPACITY              40000
#define ID_EDITCONTROL_IMPURITY                 40000
#define ID_EDITCONTROL_STEP_AMPLITUDE           40000
#define ID_EDITCONTROL_ALPHA                    40001
#define ID_EDITCONTROL_BEGIN_AMPLITUDE          40001
#define ID_EDITCONTROL_BSPLINE_ORDER            40001
#define ID_EDITCONTROL_END_BIAS                 40001
#define ID_EDITCONTROL_SAVE_PATH                40001
#define ID_MENU_SAVE_CT                         40001
#define ID_CHECKBOX_USE_ALPHA                   40002
#define ID_EDITCONTROL_BSPLINE_NCOEFFS          40002
#define ID_EDITCONTROL_END_AMPLITUDE            40002
#define ID_EDITCONTROL_STEP_BIAS                40002
#define ID_EDITCONTROL_BEGIN_BIAS               40003
#define ID_MENU_FITTING_BSPLINE                 40099
#define ID_BUTTON_NEXT_W4                       40201
#define ID_BUTTON_PREVIOUS_W4                   40203
#define ID_CHECKBOX_USE_FITTING_RELAX           40204
#define ID_BUTTON_NEXT_W2                       40205
#define ID_MENU_SAVE_SETTINGS                   40299
#define ID_MENU_SAVE_RELAXATIONS                40301
#define ID_MENU_SAVE_DLTS                       40302
#define ID_MENU_SAVE_ARRHENIUS                  40303
#define ID_MENU_OPEN                            40304
#define ID_MENU_CLEAR_MEMORY                    40308
#define ID_MENU_AUTO_PEAK_DETECTING             40309
#define ID_MAIN_WINDOW                          40310
#define ID_MAIN_MENU                            40311
#define ID_MENU_DIVIDE_S_ON_TC                  40678
